name: Run tests of relman.py
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure arbitrary Git user
        run: |
          git config --global user.name "Testy McTesterson"
          git config --global user.email "tmctesterson@users.noreply.github.com"
      - name: Install pip and Python packages
        run: |
          apt update
          apt install -y python3-pip
          pip install pylint pytest coverage
      - name: Invoke pylint
        run: pylint -E *.py
      - name: Invoke pytest
        run: pytest test.py --junit-xml=results.xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: results.xml
          path: results.xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage_info/html
