name: Run tests of relman.py
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure arbitrary Git user
        run: |
          git config --global user.name "Testy McTesterson"
          git config --global user.email "tmctesterson@users.noreply.github.com"
      - name: Invoke test.py
        run: ./test.py
