name: Run tests of relman.py
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure arbitrary Git user
        run: |
          git config --global user.name "Testy McTesterson"
          git config --global user.email "tmctesterson@users.noreply.github.com"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install Python dependencies
        run: pip install pylint pytest coverage
      - name: Invoke pylint
        run: pylint -E *.py
      - name: Invoke pytest
        run: pytest test.py --junit-xml=results.xml
